QuestionMVC/QuestionMVC/Controllers/AnswerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuestionMVC.Controllers
{
    public class AnswerController : Controller
    {
        // GET: Answer
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult getQuestionByContentId(int id,string name,string surname)
        {
            try
            {
                var classEntity = DAL.Act.GetClassEntity();
                var q = classEntity.getQuestionList(id);
                Session["User"] = classEntity.createUser(name, surname);
                List<QuestionMVC.Models.QuestionOptionListModel.QuestionListModel> qlm = new List<Models.QuestionOptionListModel.QuestionListModel>();
                foreach (var item in q)
                {
                    var x = classEntity.getOptionByQuestionId(item.Id);
                    List<QuestionMVC.Models.QuestionOptionListModel.Option> op = new List<Models.QuestionOptionListModel.Option>();
                    foreach (var item2 in x)
                    {
                        op.Add(new Models.QuestionOptionListModel.Option
                        {
                            Id = item2.Id,
                            OptionDetails = item2.OptionDetails,
                            Answer = bool.Parse(item2.Answer.ToString())
                            
                        });
                    }


                    qlm.Add(new Models.QuestionOptionListModel.QuestionListModel
                    {


                        Q = new Models.QuestionOptionListModel.Question
                        {
                            Id = item.Id,
                            QuestionDetails = item.Question1,
                            Score = Int32.Parse(item.Score.ToString())
                        },
                        O = op
                        

                    });
                }

                var u = Session["User"] as DAL.Model.Userr;
                var c = classEntity.addUserContent(u.Id, id);
              
                return PartialView("_getQuestionList",qlm);
            }
            catch (Exception)
            {

                throw;
            }
                        

        }

        public ActionResult UsersAnswers()
        {

            return View();

        }



        public JsonResult selectOption(int id)
        {

            try
            {
                var classEntity = DAL.Act.GetClassEntity();
                var u = Session["User"] as DAL.Model.Userr;
                var o = classEntity.ChooseQuestionOption(id,u.Id);
                return Json(o);

            }
            catch (Exception)
            {

                throw;
            }

        }


        public ActionResult getAlluserAnswer(int id,string password)
        {
            try
            {
                var classEntity = DAL.Act.GetClassEntity();
                var uList = classEntity.getallUserAnswerbyContentId(id);
                List<Models.UserAnswerModel.UserAnswer> ualist = new List<Models.UserAnswerModel.UserAnswer>();
                //foreach (var item in uList)
                //{
                //    foreach (var item2 in item.Userr.UserQuestionOptions)
                //    {
                //        ualist.Add(new Models.UserAnswerModel.UserAnswer
                //        {
                //            User = new Models.UserAnswerModel.UserDetails
                //            {
                //                Id = item.Userr.Id,
                //                Name = item.Userr.Name
                //            },
                //            Answers = new List<Models.UserAnswerModel.Answer>
                //            {
                //                new Models.UserAnswerModel.Answer
                //                    {
                //                     Id=item2.Question.Id,
                //                     Question=item2.Question.Question1,
                //                     Result=bool.Parse(item2.Option.Answer.ToString())
                //                    }

                //            }
                //        });
                //    }

                //}
                foreach (var item in uList)
                {
                    Models.UserAnswerModel.UserDetails u = new Models.UserAnswerModel.UserDetails();
                    u.Id = item.Userr.Id;
                    u.Name = item.Userr.Name+" "+item.Userr.Surname;
                    List<Models.UserAnswerModel.Answer> ua = new List<Models.UserAnswerModel.Answer>();
                    foreach (var item2 in item.Userr.UserQuestionOptions)
                    {
                        ua.Add(new Models.UserAnswerModel.Answer
                        {
                            Id=item2.Question.Id,
                             Question=item2.Question.Question1,
                             Result=bool.Parse(item2.Option.Answer.ToString())
                        }
                        );
                    }
                    Models.UserAnswerModel.UserAnswer uam = new Models.UserAnswerModel.UserAnswer();
                    uam.Answers = ua;
                    uam.User = u;
                    uam.Content = item.Content.Name;
                    ualist.Add(uam);
                    
                }

                



                return PartialView("_UserAnswerList",ualist);
            }
            catch (Exception ex)
            {

                throw;
            }

        }


    }
}

QuestionMVC/QuestionMVC/Views/Answer/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<div id="userque" name="userque">
    <h3><i class="fa fa-angle-right"></i> Content</h3>

    <div class="form-panel">
        <form class="form-horizontal style-form" method="get">
            <div class="form-group">
                <label class="col-sm-1 col-sm-offset-0 control-label">Name</label>
                <div class="col-sm-3">
                    <input type="text" id="uname" name="uname" class="form-control">
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-1 col-sm-offset-0 control-label">Surname</label>
                <div class="col-sm-3">
                    <input type="text" id="usurname" name="usurname" class="form-control">
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-1 col-sm-offset-0 control-label">Content Id</label>
                <div class="col-sm-2">
                    <input type="text" id="cId" name="cId" class="form-control">
                </div>
            </div>
            <div class="form-group">

                <div class="col-sm-10">
                    <a href="javascript:getQuestionByContentId()" class="btn btn-theme">GetQuestion</a>
                    <a href="javascript:finishAnswer()" class="btn btn-theme">Finish</a>
                </div>
            </div>
        </form>
    </div>
</div>
<div id="queList" name="queList">


</div>


<script>
    function getQuestionByContentId()
    {

        var data = {
            id: $('#cId').val(),
            name: $('#uname').val(),
            surname: $('#usurname').val()

        };
        
            $.ajax({
                url: '@Url.Action("getQuestionByContentId", "Answer")',
                dataType: "HTML",
                type: "POST",
                contentType: 'application/json',
                data: JSON.stringify(data),
                success: function (data) {
                    $("#queList").html(null);
                    $("#queList").html(data);
                },
                error: function (hata, ajaxOptions, thrownError) {
                    alert(hata.status);
                    alert(thrownError);
                    alert(hata.responseText);
                }
            });
     }
     function Answer(Id)
    {

         var data = {
             id: Id
        };
        if (data.id != "")
        {
        $.ajax({
            url: '@Url.Action("selectOption", "Answer")',
            dataType: "JSON",
            type: "POST",
            contentType: 'application/json',
            data: JSON.stringify(data),
            success: function (data) {
                
                getQuestionList();
            },
             error: function (hata, ajaxOptions, thrownError) {
                 alert(hata.status);
                 alert(thrownError);
                 alert(hata.responseText);
             }
         });
        }
        else {
            alert("null value");
        }

    }
    function finishAnswer() {

        window.location.assign("../Home")

    }
</script>

QuestionMVC/QuestionMVC/Views/Answer/UsersAnswers.cshtml
@{
    ViewBag.Title = "UsersAnswers";
}

<h3><i class="fa fa-angle-right"></i> Content</h3>

<div class="form-panel">
    <form class="form-horizontal style-form" method="get">
        <div class="form-group">
            <label class="col-sm-1 col-sm-offset-0 control-label">ContentId</label>
            <div class="col-sm-3">
                <input type="text" id="cId" name="cId" class="form-control">
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-1 col-sm-offset-0 control-label">Password</label>
            <div class="col-sm-3">
                <input type="text" id="password" name="password" class="form-control">
            </div>
        </div>
        <div class="form-group">

            <div class="col-sm-10">
                <a href="javascript:getAllUsersAnswer()" class="btn btn-theme">Users Answers</a>
            </div>
        </div>
    </form>
</div>

<div id="abc">

</div>
<script>
    function getAllUsersAnswer()
    {

        var data = {
            id: $('#cId').val(),
            password: $('#password').val()

        };

            $.ajax({
                url: '@Url.Action("getAlluserAnswer", "Answer")',
                dataType: "HTML",
                type: "POST",
                contentType: 'application/json',
                data: JSON.stringify(data),
                success: function (data) {
                    $("#abc").html(null);
                    $("#abc").html(data);
                },
                error: function (hata, ajaxOptions, thrownError) {
                alert(hata.status);
                alert(thrownError);
                alert(hata.responseText);
                }
                });
                }
</script>

QuestionMVC/QuestionMVC/Views/Answer/_UserAnswerList.cshtml
@model List<QuestionMVC.Models.UserAnswerModel.UserAnswer>
@*<table border="1">
        @foreach (var item in Model)
        {
                <tr>
                    <td colspan="2">@item.User.Name</td>
                </tr>

            foreach (var item2 in item.Answers)
            {
                <tr>
                    <td>@item2.Question</td>
                    <td>@item2.Result</td>
                </tr>

            }

        }
    </table>*@
  

<div class="row mt">
    <div class="col-lg-12">
        <div class="content-panel">
            <h4><i class="fa fa-angle-right"></i> Responsive Table</h4>
            <section id="unseen">
                @foreach (var item in Model)
                {
                    <table class="table table-bordered table-striped table-condensed">
                        <thead>
                            <tr>
                                <th >@item.User.Name</th>
                                <td colspan="2">@item.Content</td>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item2 in item.Answers)
                            {
                            <tr>
                                <td>@item2.Id</td>
                                <td>@item2.Question</td>
                                <td class="numeric" align="left">@item2.Result</td>
                            </tr>
                            }
                            

                        </tbody>
                    </table>
                }

            </section>
        </div>
        <!-- /content-panel -->
    </div>
    <!-- /col-lg-4 -->
</div>

QuestionMVC/QuestionMVC/Views/Answer/_getQuestionList.cshtml
@model List<QuestionMVC.Models.QuestionOptionListModel.QuestionListModel>
@foreach (var item in Model)
{
    <div class="form-panel">
        <form class="cmxform form-horizontal style-form" id="commentForm" method="get" action="">
            <h4 class="mb"><i class="fa fa-angle-right"></i> @item.Q.QuestionDetails</h4>

            @foreach (var item2 in item.O)
            {
               
                    <div class="radio">
                        <label>
                            <input type="radio" name="R" id="R" value="@item2.Id" onclick="Answer(this.value)"/>
                            @item2.OptionDetails
                        </label>
                    </div>
                }

            
        </form>
    </div>


}