QuestionMVC/QuestionMVC/Controllers/VetoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DAL.Model;

namespace QuestionMVC.Controllers
{
    public class VetoController : Controller
    {
        // GET: Veto
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult getAddVetoView(string name,string password)
        {
            var classEntity = DAL.Act.GetClassEntity();
            var c = classEntity.addContent(name,password);
            Session["Content"] = c;

            return PartialView("_AddVeto",c);
        }

        public ActionResult addVetoOption(string name)
        {
            try
            {
                var classEntity = DAL.Act.GetClassEntity();
                var c = Session["Content"] as DAL.Model.Content;
                var v = classEntity.addOptionVeto(name, c.Id);
                var vlist = classEntity.getAllVetobyContentId(c.Id);
                return PartialView("_vetoView",vlist);


            }
            catch (Exception)
            {

                throw;
            }
                        

        }

        public ActionResult VetoResult()
        {
            return View();
        }


        public ActionResult AnswerVeto(int id,string password)
        {
            try
            {
                var classEntity = DAL.Act.GetClassEntity();
                var v = classEntity.getAllVetobyContentId2(id, password);
                return PartialView("_VetoesListView",v);
            }
            catch (Exception)
            {

                throw;
            }


        }

        public ActionResult getResult(int id)
        {
            try
            {
                var classEntity = DAL.Act.GetClassEntity();
                var v = classEntity.getAllVetobyVetoId(id);
                return PartialView("_getResult", v);
            }
            catch (Exception ex)
            {

                throw;
            }

        }

        public JsonResult VetoOp(int id)
        {
            var classEntity = DAL.Act.GetClassEntity();
            var v = classEntity.PlusVetoCount(id);
            return Json(v.ContentId);

        }

    }
}

QuestionMVC/QuestionMVC/Views/Veto/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h3><i class="fa fa-angle-right"></i> Content</h3>

<div class="form-panel">
    <form class="form-horizontal style-form" method="get">
        <div class="form-group">
            <label class="col-sm-1 col-sm-offset-0 control-label">Content Title</label>
            <div class="col-sm-3">
                <input type="text" id="cname" name="cname" class="form-control">
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-1 col-sm-offset-0 control-label">Password</label>
            <div class="col-sm-2">
                <input type="text" id="cpassword" name="cpassword" class="form-control">
            </div>
        </div>
        <div class="form-group">

            <div class="col-sm-10">
                <a href="javascript:addContent()" class="btn btn-theme">Add</a>
                <a href="javascript:FinishContent()" class="btn btn-theme">Finish</a>
            </div>
        </div>
    </form>
</div>
<div id="veto">

</div>
<script>
function addContent()
    {
        var data = {
            name: $('#cname').val(),
            password: $('#cpassword').val()

        };

            if (data.name != "" && data.password != "")
            {

                $.ajax({
                    url: '@Url.Action("getAddVetoView", "Veto")',
                    dataType: "HTML",
                    type: "POST",
                    contentType: 'application/json',
                    data: JSON.stringify(data),
                    success: function (data) {
                        $("#veto").html(null);
                        $("#veto").html(data);
                    },
                    error: function (hata, ajaxOptions, thrownError) {
                    alert(hata.status);
                    alert(thrownError);
                    alert(hata.responseText);
                    }
                    });
            }
                else
                {
                alert("null value");
                }
    }


    function addVetoOptions()
    {
        var data = {
            name: $('#vname').val()

        };

            if (data.name != "")
            {

                $.ajax({
                    url: '@Url.Action("addVetoOption", "Veto")',
                    dataType: "HTML",
                    type: "POST",
                    contentType: 'application/json',
                    data: JSON.stringify(data),
                    success: function (data) {
                        $("#optionList").html(null);
                        $("#optionList").html(data);
                    },
                    error: function (hata, ajaxOptions, thrownError) {
                    alert(hata.status);
                    alert(thrownError);
                    alert(hata.responseText);
                    }
                    });
            }
                else
                {
                alert("null value");
                }
    }


    function FinishContent() {

       

         $.ajax({
            url: '@Url.Action("finishContent", "Home")',
            dataType: "JSON",
            type: "POST",
            contentType: 'application/json',
             success: function (data) {
                 alert(data);
                window.location.assign("../Home");
                
            },
             error: function (hata, ajaxOptions, thrownError) {
                 alert(hata.status);
                 alert(thrownError);
                 alert(hata.responseText);
             }
         });
       

    }

</script>

QuestionMVC/QuestionMVC/Views/Veto/VetoResult.cshtml
@{
    ViewBag.Title = "VetoResult";
}

<h3><i class="fa fa-angle-right"></i> Result </h3>

<div class="form-panel">
    <form class="form-horizontal style-form" method="get">
        <div class="form-group">
            <label class="col-sm-1 col-sm-offset-0 control-label">Content Title</label>
            <div class="col-sm-3">
                <input type="text" id="cId" name="cId" class="form-control">
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-1 col-sm-offset-0 control-label">Password</label>
            <div class="col-sm-2">
                <input type="text" id="cpassword" name="cpassword" class="form-control">
            </div>
        </div>
        <div class="form-group">

            <div class="col-sm-10">
                <a href="javascript:AnswerVeto()" class="btn btn-theme">Get Result</a>
            </div>
        </div>

    </form>
</div>

<div id="vetoAnswer">


</div>


<script>

    function AnswerVeto()
    {
        var data = {
            id: $('#cId').val(),
            password: $('#cpassword').val()

        };

        if (data.id != "" && data.password != "")
        {

            $.ajax({
                url: '@Url.Action("AnswerVeto", "Veto")',
                dataType: "HTML",
                type: "POST",
                contentType: 'application/json',
                data: JSON.stringify(data),
                success: function (data) {
                    $("#vetoAnswer").html(null);
                    $("#vetoAnswer").html(data);
                },
                error: function (hata, ajaxOptions, thrownError) {
                    alert(hata.status);
                    alert(thrownError);
                    alert(hata.responseText);
                }
            });
        }
        else
        {
            alert("null value");
        }
    }

    function Veto(Id)
    {
        var data = {
            id: Id

        };

        if (data.id != "")
        {

            $.ajax({
                url: '@Url.Action("VetoOp", "Veto")',
                dataType: "JSON",
                type: "POST",
                contentType: 'application/json',
                data: JSON.stringify(data),
                success: function (data) {
                    getR(data)
                },
                error: function (hata, ajaxOptions, thrownError) {
                    alert(hata.status);
                    alert(thrownError);
                    alert(hata.responseText);
                }
            });
        }
        else
        {
            alert("null value");
        }
    }

    function getR(Id)
    {
        var data = {
            id: Id

        };

        if (data.id != "")
        {

            $.ajax({
                url: '@Url.Action("getResult", "Veto")',
                dataType: "HTML",
                type: "POST",
                contentType: 'application/json',
                data: JSON.stringify(data),
                success: function (data) {
                    $("#vetoAnswer").html(null);
                    $("#vetoAnswer").html(data);
                },
                error: function (hata, ajaxOptions, thrownError) {
                    alert(hata.status);
                    alert(thrownError);
                    alert(hata.responseText);
                }
            });
        }
        else
        {
            alert("null value");
        }
    }



</script>

QuestionMVC/QuestionMVC/Views/Veto/_AddVeto.cshtml
@model DAL.Model.Content
<h2><i class="fa fa-angle-right"></i> @Model.Name </h2>
<div class="form-panel">
    <div class=" form">
        <form class="cmxform form-horizontal style-form" id="commentForm">
            <div class="form-group ">
                <label for="cname" class="control-label col-lg-1">Option</label>
                <div class="col-lg-10">
                    <input class=" form-control" id="vname" name="vname" minlength="2" type="text" required="">
                </div>
            </div>
            <div id="optionList">

            </div>

            <div class="form-group">

                <div class="col-sm-10">
                    <a href="javascript:addVetoOptions()" class="btn btn-theme">Add Veto Option</a>
                    <a href="javascript:FinishContent()" class="btn btn-theme">Finish</a>
                </div>
            </div>

        </form>
    </div>
</div>

QuestionMVC/QuestionMVC/Views/Veto/_VetoesListView.cshtml
@model  DAL.Model.Content
<div class="form-panel">
    <h4 class="mb"><i class="fa fa-angle-right"></i> Checkboxes, Radios &amp; Selects</h4>
    @foreach (var item in Model.Vetoes)
    {
           <div class="radio">
                <label>
                    <input type="radio" name="Vıd" id="Vıd" value="@item.Id" onclick="Veto(this.value)" />
                    @item.Name
                </label>
            </div>
        
    }
</div>
   

QuestionMVC/QuestionMVC/Views/Veto/_getResult.cshtml
@model List<DAL.Model.Veto>

<div class="col-lg-6">
    @foreach (var item in Model)
    {<div class="content-panel">
            <h4><i class="fa fa-angle-right"></i>@item.Name  @item.Count</h4>
        </div>
    }
</div>
    

QuestionMVC/QuestionMVC/Views/Veto/_vetoView.cshtml
@model List<DAL.Model.Veto>
<div class="form-group">

    <div class="col-sm-10">
        <table>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Name</td>
                </tr>
            }

        </table>
    </div>
</div>